
server:
  port: 8989
spring:
  application:
    name: rss-inventory-service
  cloud:
    kubernetes:
      discovery:        all-namespaces: true
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate_sql: true
    show-sql: true
management:
  metrics:
    export:
      prometheus:
        # enabling prometheus format metrics
        enabled: true   endpoints:    web:      exposure:        include: "*"  endpoint:    health:      enabled: true     
