
server:
  port: 9999
spring:
  application:
    name: rss-inventory-service
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate_sql: true
    show-sql: true
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true      

# if application.properties is not working, add the environment variables here